### ISSUE TITLE
Native Heap memory leaking

### ISSUE THREAD

**Issue by henritta** [koral--/android-gif-drawable#105]
Dear koral,

I use instruction to dump memory info several times.

ex: dumpsys meminfo -p pl.droidsonroids.gif.sample

I found the Native Heap always group up, even thought I did nothing, just play the same Gif pictures,

not leaving the activity, or go any other ap/activity.

You can try and see Pss Total Native Heap column.

I try tracing the c code as below,

    container->buffer = (*env)->NewGlobalRef(env, bytes);
    container->arrLen = (*env)->GetArrayLength(env, container->buffer);
    container->pos = 0;
    int Error;
    GifFileType *GifFileIn = DGifOpen(container, &byteArrayReadFun, &Error);

    jobject gifInfoHandle = createGifHandle(GifFileIn, Error, container->pos, byteArrayRewind, env, justDecodeMetaData);

    if (gifInfoHandle == NULL) {
        (*env)->DeleteGlobalRef(env, container->buffer);
        free(container);
    }
    return gifInfoHandle;

//======================================================
I found,

container-> buffer allocates a global ref, but it is only deleted when gifInfoHandle is null,

and in createGifHandle, container->buffer is not used and not deleted.

I guess that might be one of the leak reasons.

Please help to check, thanks.

**Comment by henritta** [comment]
Hi koral,

I seen you resolve this problem, thanks a lot.

I try your patch.  I think there have some new problems.

1. Animation play for a while the image color will change to black-white

2. Play a few time and press back key, I found some error logs

A/libc(4765): chunk ptr "p" is invalid with any segment
A/libc(4765): invalid address or address of corrupt block 0x8 passed to dlfree

I think that might have error in free(Object->Colors) of GifFreeMapObject function.

And after this error msg, enter the activity again,
it won't play anymore and press back key will cause ANR.

Means I have to kill process to prevent such problem.

**Comment by henritta** [comment]
Hi Koral,

I made some modification in DGifGetImageDesc function as following:

    if (changeImageCount)
    {
		if (GifFile->SavedImages) {
			if ((GifFile->SavedImages = (SavedImage *)realloc(GifFile->SavedImages,
										  sizeof(SavedImage) *
										  (GifFile->ImageCount + 1))) == NULL) {
				GifFile->Error = D_GIF_ERR_NOT_ENOUGH_MEM;
				return GIF_ERROR;
			}
		} else {
			if ((GifFile->SavedImages =
				 (SavedImage *) malloc(sizeof(SavedImage))) == NULL) {
				GifFile->Error = D_GIF_ERR_NOT_ENOUGH_MEM;
				return GIF_ERROR;
			}
		}

        sp = &GifFile->SavedImages[GifFile->ImageCount];
        memcpy(&sp->ImageDesc, &GifFile->Image, sizeof(GifImageDesc));

        if (GifFile->Image.ColorMap != NULL) {
            sp->ImageDesc.ColorMap = GifMakeMapObject(
                                     GifFile->Image.ColorMap->ColorCount,
                                     GifFile->Image.ColorMap->Colors);
            if (sp->ImageDesc.ColorMap == NULL) {
                GifFile->Error = D_GIF_ERR_NOT_ENOUGH_MEM;
                return GIF_ERROR;
            }
        }
        sp->RasterBits = (unsigned char *)NULL;
        sp->ExtensionBlockCount = 0;
        sp->ExtensionBlocks = (ExtensionBlock *) NULL;

        GifFile->ImageCount++;
    }

And the result of native heap leak looks good. 

I guess that is because it always allocates memory for last frame and does memcpy the data to last GifFile->SavedImages. After modifying, it only allocates each frame once and does not reallocate for last frame when rendering frame.

Please help double check if it is the root cause and a possible solution. 
Thank you so much.

**Comment by koral--** [comment]
Generally speaking you are right.
Precisely: cause of the leak is that `GifMakeMapObject` was called unconditionally while it is needed only when `changeImageCount` is true. Other code are unnecessary but it did not increase amount of allocated memory. `ImageCount` is constant when `changeImageCount` is false so after calling `realloc`  allocated heap size does not change. Of course is it is good idea not to execute useless code and wrap all the code with `if (changeImageCount)`. It will improve performance.
I've made even a little more improvement: realloc of NULL pointer works like a malloc so it is not needed to check.

Additionally I've found other probable little issues:
+ if `realloc` (other than first one) fails (due to out of memory) then `SavedImages` becomes NULL and leak occurs (previously allocated memory is not reachable and won't be freed during cleanup). That was fixed in GIFLIB 5.1.1 relased yesterday. I'll update to that version ASAP.
+ if `GifMakeMapObject` returns NULL then `RasterBits`, `ExtensionBlockCount` and `ExtensionBlocks` will remain unitialized so heap corruption may occur during freeing on cleanup. They should probably be initialized before calling `GifMakeMapObject` and that can be reported as bug in GIFLIB I think. I'll check that.
