### ISSUE TITLE
Checking that the gif is stopped

### ISSUE THREAD

**Issue by DmitriyZaitsev** [koral--/android-gif-drawable#129]
Hi Karol.
Not a bug, but suggestion. As you remember #125, there was the file with loop count = 1. It would be very nice if we can ask ```GifDrawable``` either is it playing right now or not.
```GifDrawable``` has methods ```isRunning()``` and ```isPlaying()```, but they always return ```true``` if drawable isn't recycled. They, in fact, identical. Also identical ```pause()``` and ```stop()```.
So, it would be very nice, for example, if gif finished playing ```isRunning()``` returned ```true``` but ```isPlaying()``` returned ```false```.
Or maybe you can add smth like ```isLoopFinished()```, you know. Or maybe you can tell me how I can check the drawable played the only loop and stopped.

**Comment by koral--** [comment]
`stop()` and `isRunning()` are overriden from `Animatable` while `pause()` and `isPlaying()` from `MediaPlayerControl` although their jobs are respectively the same.
Currently it is not possible to check directly if animation is finished. Indirect way is to register animation listener.
I rethought all related flow and realized that more changes are needed in that matter:
* return false from `isRunning()` / `isPlaying()` in all cases if animation is not really running (currently it is false only when `stop()` or `pause()` is called explicitly or drawable is recycled. One missing case except that which you mentioned is when animation is stopped because input reading error occurred (eg. drawable was made from file on SD card which was removed)
* fire `AnimationListener#onAnimationCompleted()` if all loops are completed, not on each loop (with exception in case when animation is endless)
* add methods `getCurrentFrameIndex()` and `getCurrentLoop()` so in conjunction with existing methods it will be possible to check if loop is finished (not only one but every n-th)
