### ISSUE TITLE
seekToFrame() and seekTo() off by one frame

### ISSUE THREAD

**Issue by agrajaghh** [koral--/android-gif-drawable#150]
I'm having a problem with `seekToFrame()` and `seekTo()`:

at `seekToFrame()` there is written:
> frameIndex index of the frame to seek to **(zero based)**

but `seekToFrame(0)` is giving me an empty Bitmap (with `getCurrentFrame()`).
`seekToFrame(1)` is giving me the first frame, not the second.

The same problem exists with `seekTo()`:
`seekTo(80)` gives me an empty Bitmap, but `seekTo(81)` gives me the first frame. (80ms duration)

I used this gif (but tested some other gifs as well):
![users](https://cloud.githubusercontent.com/assets/5296073/7220748/43784b6c-e6d3-11e4-9fb3-d54c876f07ad.gif)

another question: 
Is it possible to get the duration of the current frame? `getDuration() / getNumberOfFrames()` doesn't work if the durations are different for each frame...

**Comment by agrajaghh** [comment]
Thanks for your quick fix! I just tested the dev branch and `seekToFrame()` and `goToFrame()` work as expected :blush: 

But `goToPosition()` and `seekTo()` seem to be off by 1ms. I tested with this gif consisting of 4 frames each 50ms:
![numbergif](https://cloud.githubusercontent.com/assets/5296073/7228585/e4b558da-e75a-11e4-9e83-06caf75b3a3f.gif)

`goToPosition(0)` gives the first frame
`goToPosition(50)` **gives the first frame**, I would expect the second frame
`goToPosition(51)` gives the second frame

**Comment by koral--** [comment]
OK, so one after the other:
1. there was a bug that corner values were not handled properly when seeking, after f1bed87 it should be fixed
2. `seekToFrame()`/`seekTo()` works asynchronously (seeking is done in render thread) so if you call `getCurrentFrame()` immediately after in the caller thread it may return inconsistent bitmap (it only copies current content of the frame buffer) because seeking may be in progress. For case like yours I've added `goToFrame()` which is now renamed to `seekToPositionAndGet()`/`seekToFrameAndGet()` which is synchronous and atomically acquires frame buffer after seeking.
3. I've added `getFrameDuration(int index)` method to get duration of the particular frame.

**Comment by agrajaghh** [comment]
Perfect, thanks again :+1: 

I realized that the old seek methods were async, so I used an own TaskExecutor and did something like that:
````java
mGifDrawable.seekTo(frameTimeMillis);
while (mGifTaskExecutor.getActiveCount() > 0) {
	Thread.sleep(1);
}
Bitmap bmp = mGifDrawable.getCurrentFrame();
````

`seekToPositionAndGet()/seekToFrameAndGet()` is of course much better :blush:
