### ISSUE TITLE
animated gifs flashing partially

### ISSUE THREAD

**Issue by dangalg** [koral--/android-gif-drawable#162]
I display the animated gifs in an arrayadapter in a tabbed layout. They are randomly flashing the background color, as if they are not displaying correctly.

**Comment by koral--** [comment]
Are you using the latest library version (1.1.6)? If so please attach example of flashing GIF? If not, try the latest version. There was bug with flashing background (#122), but it has been resolved.

**Comment by dangalg** [comment]
Yes using latest version. it is only flashing when I am using animted gifs with transperancy

![dan](https://cloud.githubusercontent.com/assets/5820649/7454284/c0818986-f27a-11e4-87ed-c3bbda6ca684.gif)

**Comment by dangalg** [comment]
this is how my viewpager looks. I am unable to capture the flashes... the camera is too slow
![quickmemo _2015-05-04-16-31-43](https://cloud.githubusercontent.com/assets/5820649/7454366/b2bb23ec-f27b-11e4-9553-bfe15a2f2527.png)

**Comment by dangalg** [comment]
I managed to shoot this video of the problem (and converted it to a gif). please look at the gif on top left.


![demo](https://cloud.githubusercontent.com/assets/5820649/7455080/ea3880d4-f281-11e4-82dd-0cf027cfeeaf.gif)

**Comment by koral--** [comment]
OK, I'll check this.

**Comment by dangalg** [comment]
Thanx!

**Comment by koral--** [comment]
Is flashing still visible when hardware acceleration is turned off? Eg. by setting `android:hardwareAccelerated="false"` in manifest (inside `application` tag).

**Comment by dangalg** [comment]
inside application tag or activity tag?

**Comment by dangalg** [comment]
I put it both in application tag and in activity tag and it is still happening

**Comment by dangalg** [comment]
when I put hardware accelerated true. it works much better. the whole phone works better. the only problem is that that one animated gif moves a little bit and then is stuck.

**Comment by dangalg** [comment]
Ok I did a few configurations:

hardware_accelerated = false
![hardware-accelerated-false](https://cloud.githubusercontent.com/assets/5820649/7467350/71d61196-f2ff-11e4-982a-d34bc45e3fc7.gif)
result: lag and flashing

hardware_accelerated = true and in my view pager I put setOffscreenPageLimit = 0
![hardware-accelerated-true-setoffscreenpagelimit-0](https://cloud.githubusercontent.com/assets/5820649/7467357/acb4ec4c-f2ff-11e4-8625-bfb4075f1dc3.gif)
result: no lag and no flashing but one gif spins then goes back to the beginning and is stuck. but when I move 2 tabs ahead it works normally. if I swipe tab by tab it is stuck.

hardware_accelerated = true and in my view pager I put setOffscreenPageLimit = 2
![hardware-accelerated-true-setoffscreenpagelimit-2](https://cloud.githubusercontent.com/assets/5820649/7467361/b7c07066-f2ff-11e4-999b-2acc08c631bf.gif)
result: no lag and no flashing but one gif spins then goes back to the beginning and is stuck. but when I move 3 tabs ahead it works normally. if I swipe tab by tab it is stuck.

conclusions:
I must hardware_accelerated = true, because without it the app is very laggy
There is only one gif that is making problems and it is this one:
![dan](https://cloud.githubusercontent.com/assets/5820649/7467372/ef1767a4-f2ff-11e4-979a-16befa43c1e0.gif)
If moving a few tabs ahead fixes the problem when hardware_accelerated = true, maybe it has something to do with the fragments refreshing.

**Comment by dangalg** [comment]
ok I found out something. I replaced that first gif putting a different gif in the first spot and now it is stuck. so I think this issue has nothing to do with your code or the specific gif, but something to do with my code. Also it works great with hardware accelerated set as true on my galaxy s2 running 4.1.2 and my lg g3 running lollipop.
You are awesome. thanks!

**Comment by koral--** [comment]
I noticed that sometimes when there is a lot of drawing operations on hardware accelerated `Canvas` (lot of GIFs and/or high frame rate) there are artifacts like black or white lines. `E/OpenGLRenderer﹕ Cannot generate texture from bitmap` appears in logcat in such cases. I don't know (yet) how to fix that. Actually problem is located outside this library so I can only make workarounds like drawing in different way.

Problem with freezing animations in adapter has been reported here: https://github.com/koral--/android-gif-drawable/issues/135#issuecomment-91653973
It turns out that `getView()` is called several times for first item as you said and displayed drawable in first item has no callback. Look at next comments in linked issue to see proposed solutions.

If want only to display animations (without using `Drawable` specific features) and have target API level set to 14+, you can use `GifTextureView`. There is no canvas nor callback so it should be unaffected to problems mentioned in your last post.

**Comment by koral--** [comment]
I am closing this issue since discussion happens in #135.

**Comment by koral--** [comment]
I am closing this issue since discussion happens in #135.
