### ISSUE TITLE
heap corruption for some gifs

### ISSUE THREAD

**Issue by lingangAaron** [koral--/android-gif-drawable#218]
Hi Koral
I used this in my app ， but met heap corruption . i set the bad gif and the normal gif in turns for test for A certain number of times . the bad gif provided below . i just don't why ? May you just look at this issue .

new the GifDrawable
mDrawable = new GifDrawable(path);
setImageDrawable(mDrawable);

when recycle it when detachWindow
 mDrawable.recycle();
 mDrawable = null;

it surely call GifInfoHandle recycle
but the heap grow up a little every turn and just the gif below 
![111](https://cloud.githubusercontent.com/assets/11925818/10542622/1635b49e-744c-11e5-9452-ec56122313cc.gif)

i'm not good at English ==!

**Comment by lingangAaron** [comment]
Hello Hello ?

**Comment by koral--** [comment]
OK, I'll check that.

**Comment by lingangAaron** [comment]
i just found not only some gifs , other gifs no heap corruption before now has little ....it's weird.

**Comment by lingangAaron** [comment]
i add 
if (GifFile->Private != NULL) {
    	free(GifFile->Private);
    	GifFile->Private = NULL;
    }
    if(info->gifFilePtr != NULL){
    	free(info->gifFilePtr);
    	info->gifFilePtr = NULL;
    } 
in cleanup , but  not work
I try to call this GifFreeSavedImages in cleanup , but app is freeze....==

**Comment by koral--** [comment]
How are you checking heap size?
`GifFile->Private` and `info->gifFilePtr` are already freed (see `dgif_lib.c`).

**Comment by lingangAaron** [comment]
adb shell dumpsys meminfo
the native heap is growing

**Comment by lingangAaron** [comment]
i user the older version not calling DGifCloseFile int cleanup 
i download the last it surely called ....

**Comment by koral--** [comment]
I could not reproduce heap corruption using that GIF loaded from path.
Note that `dumpsys meminfo` shows info about all memory of an app, not only that allocated by this library thus returned numbers may change even if no library code is executed.

**Comment by lingangAaron** [comment]
ok， i’ll check my code .
any way thanks a lot

**Comment by lingangAaron** [comment]
Hi koral,
i don't how to check or locate the heap corruption in native heap like so file
would you please give some available way to work on it or some tools you used ?
Thanks very much

**Comment by koral--** [comment]
There are several tools eg. [Valgrind](http://valgrind.org/) and [AddressSanitizer](https://source.android.com/devices/tech/debug/asan.html). Note that app will extremely slow down when run under Valgrind, it may take several minutes to start an Activity. Moreover memory allocated in `JNI_OnLoad()` may be listed as reachable in loss record, it is not a bug because `JNI_OnUnload()` (when that memory is freed) is never called on most (if not all) Android ROMs.

Another useful way is to use [mallinfo](http://man7.org/linux/man-pages/man3/mallinfo.3.html) from native code. Summary results will be equal to that returned by `dumpsys meminfo` but `mallinfo` may be invoked in precisely defined moments.
