### ISSUE TITLE
[Question] About ReLinker and Android NDK

### ISSUE THREAD

**Issue by huyduongtu** [koral--/android-gif-drawable#242]
```
File outputFile = new File(context.getDir(LIB_DIR, Context.MODE_PRIVATE), libName + BuildConfig.VERSION_NAME);
        if (outputFile.isFile()) {
            return outputFile;
        }

        final File cachedLibraryFile = new File(context.getCacheDir(), libName + BuildConfig.VERSION_NAME);
        if (cachedLibraryFile.isFile()) {
            return cachedLibraryFile;
        }
```

In method `unpackLibrary()` of class `ReLinker`, why do you include `BuildConfig.VERSION_NAME`?
What is it for?

Why do you have to build 2 separate .so files? `libpl_droidsonroids_gif.so` and `libpl_droidsonroids_gif_surface.so`. 
 It's better to make them as one file. I see that the lib just load the file `libpl_droidsonroids_gif.so`. So can I remove the file `libpl_droidsonroids_gif_surface.so` to reduce apk size?

**Comment by koral--** [comment]
Why `BuildConfig.VERSION_NAME` is appended?
In a nutshell there is a bug in certain versions of Android’s PackageManager which causes native library loading issues after app update. This is a part of a workaround for that issue. Normally native libraries should be extracted by PackageManager from APK to certain directory in internal storage, replaced on app update and loaded when `System.loadLibrary()` is called.
If library cannot be loaded normally, it is extracted using ReLinker from APK into internal storage. That file persists across app updates so to support case when version of library is changed on app update, that number is appended to filename.
See [that aricle](https://medium.com/keepsafe-engineering/the-perils-of-loading-native-libraries-on-android-befa49dce2db#.rupof2tgp) and linked Chromium sources (which uses similar technique).

Why there are 2 .so files?
Native window API is available since API level 9 but current `minSdkVersion` of library is 8. Loading `libpl_droidsonroids_gif_surface.so` on device with API 8 will cause an error. It is loaded here in `GifTextureView`: https://github.com/koral--/android-gif-drawable/blob/master/src/main/java/pl/droidsonroids/gif/GifTextureView.java#L103 and that code might be executed only on API level 14+. So you cannot remove `libpl_droidsonroids_gif_surface.so` if you are using `GifTextureView`.

Is it better to have 1 .so file instead of 2?
It depends. The same source code compiled to single .so file will occupy a little bit less disk space but on the other hand even if `GifTextureView` is not used, native code supporting it will be always loaded increasing needed memory size. Few lines of java code can be removed but support of API level 8 must be either dropped or done in different way.

**Comment by huyduongtu** [comment]
Thanks for your quick reply. 
So I wanna make a android library module for GifDrawable. And don't wanna change the version of the library in future. So can I remove ```BuildConfig.VERSION_NAME``` in ReLinker?
For the ReLinker works normally, I have to call LibraryLoader.initialize() firstly?

**Comment by koral--** [comment]
`BuildConfig.VERSION_NAME` is generated automatically by gradle from properties file at the compile time. It is a version of library module defined here: https://github.com/koral--/android-gif-drawable/blob/master/gradle.properties#L1 
`LibraryLoader.initialize()` should be called.

**Comment by huyduongtu** [comment]
Can I define ```BuildConfig.VERSION_NAME``` in ```AndroidManifest.xml``` or ```build.gradle``` in library module?

When I go to definition (F3) of  ```BuildConfig.VERSION_NAME``` in class ReLinker. It jump into BuildConfig.java of library module with ```VERSION_NAME``` is "1.0", not the value (1.1.11) defined in properties file.
![zalo_screenshot_11_1_2016_1028428](https://cloud.githubusercontent.com/assets/6157839/12226426/65fa0e8a-b84e-11e5-9497-90d4c5f13e66.png)

**Comment by koral--** [comment]
Flow of version name is as follows:
1. it is defined as a property in `gradle.properties` - https://github.com/koral--/android-gif-drawable/blob/master/gradle.properties#L1
2. `project.version` is assigned - https://github.com/koral--/android-gif-drawable/blob/master/build.gradle#L19
3. `android.defaultConfig.versionName` is assigned - https://github.com/koral--/android-gif-drawable/blob/master/build.gradle#L30
4. at compile time `BuildConfig.java` is generated by gradle using the latter

This is content of `BuildConfig` class included in aar on maven central:
```java
package pl.droidsonroids.gif;

public final class BuildConfig
{
  public static final boolean DEBUG = false;
  public static final String APPLICATION_ID = "pl.droidsonroids.gif";
  public static final String BUILD_TYPE = "release";
  public static final String FLAVOR = "";
  public static final int VERSION_CODE = -1;
  public static final String VERSION_NAME = "1.1.11";
}
```

So it looks like you have changed `android.defaultConfig`.

`gradle-mvn-push.gradle` is used for maven repository related stuff - aritfact generation (including javadoc), upload etc. You can ignore this file if you need just to use library in your project.

`ndk.gradle` is used for NDK related stuff. Most of the content is needed to successfully compile native code. If you have remove all its content but pasted snippet then you have probably not built .so files but just used previously generated files. The most important part is `buildNative` task definition here: https://github.com/koral--/android-gif-drawable/blob/master/ndk.gradle#L51 without that no native code is compiled.
If you want to keep as less code as possible then you can try following changes:
- remove all flavor related code from `ndk.gradle` (like https://github.com/koral--/android-gif-drawable/blob/master/ndk.gradle#L66) it is a workaround for build failure with Nokia X SDK on Windows
- remove detection if it is a debug or release build -  hardcode result of `isDebugBuild()`: https://github.com/koral--/android-gif-drawable/blob/master/ndk.gradle#L48
- remove OS detection and hardcode result of `getNdkBuildCommand()` - https://github.com/koral--/android-gif-drawable/blob/master/ndk.gradle#L33

**Comment by huyduongtu** [comment]
Thanks for your very detailed answer.
But as I said before, I just used that pasted snippet
```
sourceSets.main {
        jni.srcDirs = []
        jniLibs.srcDir 'src/main/libs'
    }
```
To build the .so files, I run ```ndk-build``` from command line. It successfully generated those .so files. Currently I can apply them in my project. I think the code in ```ndk.gradle``` is used for automatically generate so files by Android Studio when pressing build project? Right?
Besisdes,  because I don't use ```GifTextureView```, I modify a little in ```Android.mk``` to just generate a single .so file.

**Comment by koral--** [comment]
You haven't mentioned that you used `ndk-build' from commandline manually. If you do this then indeed files are compiled. Gradle task `buildNative` invokes `ndk-build` with appropriate parameters when project is compiled. So if you have it in gradle scripts then you don't need to invoke `ndk-build` manually.

**Comment by huyduongtu** [comment]
OK. Thanks you very much.
