### ISSUE TITLE
OutOfMemoryError with a small gif

### ISSUE THREAD

**Issue by huyduongtu** [koral--/android-gif-drawable#243]
The sample always crashes when I wanna display this gif file, even with GifTextureView or GifDrawable. The gif url is http://dl.file.zalo.zdn.vn/2d6539022542cc1c9553/1165032654979416611

Here is the crash log. In ```HttpFragment```
```
 [unnamed-14842-0] detachFromContext: abandoned GLConsumer
01-15 08:56:21.380 14842-14869/pl.droidsonroids.gif.sample E/OpenGLRenderer: Failed to detach SurfaceTexture from context -19
01-15 08:56:21.684 14842-15018/pl.droidsonroids.gif.sample E/AndroidRuntime: FATAL EXCEPTION: GifRenderThread
        Process: pl.droidsonroids.gif.sample, PID: 14842
        java.lang.OutOfMemoryError: Failed to allocate native memory
        at pl.droidsonroids.gif.GifInfoHandle.openByteArray(Native Method)
        at pl.droidsonroids.gif.InputSource$ByteArraySource.open(InputSource.java:92)
        at pl.droidsonroids.gif.GifTextureView$RenderThread.run(GifTextureView.java:181)
```

This gif file is resized down. The original file is big. I debug and see that, width = 188 , height = 103. But at some frames, left = 26020 and top = 28016. That causes the Ginfo->rasterBits size finally is so big -> OutOfMemoryError.
https://github.com/koral--/android-gif-drawable/blob/master/src/main/jni/decoding.c#L17,L18.
Why did you do like that? I just try modifying like this:
```
const uint_fast16_t requiredScreenWidth = info->gifFilePtr->Image.Width;
const uint_fast16_t requiredScreenHeight = info->gifFilePtr->Image.Height;
```
It works fine. All frame are displayed normally.

**Comment by koral--** [comment]
GIFs can contain canvas (background common to all frames) which have given dimensions. Additionally each frame (image) has its own dimensions (width, height) and offset (left, top). Eg. one can have canvas 100x100, frame 1. 10x10 with offset 0,0 (so frame is aligned to the top-left of the canvas), frame 2. 10x10, with offset 50(left), 50(top) (so it will start in the centre), etc. See here for more information: http://giflib.sourceforge.net/whatsinagif/bits_and_bytes.html

Ideally frames should be confined into a canvas, eg. if canvas is 100x100 and frame 10x10, its left and top should be lesser or equal to 90.

I assumed that if frame would be located outside a canvas it should be expanded appropriately so every frame can be drawn at requested position. It turns out not good solution.

I just looked at skia source code, and they are expanding a canvas if frame size exceeds its size, but shifting a frame if it would be located outside a canvas: https://github.com/google/skia/blob/master/src/images/SkImageDecoder_libgif.cpp#L299
So every frame will be drawn completely even if it is larger than a canvas, optionally it may be shifted.
I'll implement that ASAP.

It looks like your solution is incomplete. It will fail for cases when frame size is not larger than a canvas size but including offset it will be partially outside a canvas. Namely in this line: https://github.com/koral--/android-gif-drawable/blob/33fcba259e6917b4aea02dfe57277e6f69d996ae/src/main/jni/drawing.c#L15 heap corruption will occur.

**Comment by huyduongtu** [comment]
I changed my solution. If a frame size exceeds canvas size, I'll modify it's size and left, top to confine into the canvas.
The following code in `DGifGetImageDesc`
```
if (DGifGetWord(GifFile, &GifFile->Image.Left) == GIF_ERROR ||
        DGifGetWord(GifFile, &GifFile->Image.Top) == GIF_ERROR ||
        DGifGetWord(GifFile, &GifFile->Image.Width) == GIF_ERROR ||
        DGifGetWord(GifFile, &GifFile->Image.Height) == GIF_ERROR)
        return GIF_ERROR;

    //Resize Frame Descriptor if size is bigger than header's size.
    if (GifFile->Image.Width >= GifFile->SWidth) {
        GifFile->Image.Width = GifFile->SWidth;
        GifFile->Image.Left = 0;
    } else if(GifFile->Image.Left + GifFile->Image.Width > GifFile->SWidth) {
        GifFile->Image.Left = 0;
    }

    if (GifFile->Image.Height >= GifFile->SHeight) {
        GifFile->Image.Height = GifFile->SHeight;
        GifFile->Image.Top = 0;
    } else if(GifFile->Image.Top + GifFile->Image.Height > GifFile->SHeight) {
        GifFile->Image.Top = 0;
    }
```

**Comment by huyduongtu** [comment]
Besides that, I see `DDGifSlurp(info, true)` is called every rendering frame. `DDGifSlurp` is to collect information of all frames. With my solution above, the canvas doesn't change, jut fit with header size.
It's not necessary to call `DDGifSlurp(info, true)` every rendering frame to improve performance. Is it right?

**Comment by koral--** [comment]
I've already solved a problem using linked approach from skia. 
Coming back to your last snippet, lowering frame size implies that extraneous bytes need to be discarded when reading raster data. If you don't do that then decoding fail on next frame (start of next frame is expected, but leftover pixel data is present. Look here: https://github.com/koral--/android-gif-drawable/blob/master/src/main/jni/decoding.c#L54
And obviously it is a little bit better to decode whole frame instead of discarding some part of it.

Answer to your last question is no. `DDGifSlurp(info, true)` needs to be called on every frame, if `shouldDecode==true` then only one (current) frame is read and decoded. See `return` statement here: https://github.com/koral--/android-gif-drawable/blob/master/src/main/jni/decoding.c#L59. In `createGifHandle()` that parameter is `false` which means that all frames are read, but no pixel data is decoded.

**Comment by huyduongtu** [comment]
Please show me your solution.

**Comment by koral--** [comment]
* New code is pushed to dev branch: https://github.com/koral--/android-gif-drawable/tree/dev. Here is relevant part: https://github.com/koral--/android-gif-drawable/blob/dev/src/main/jni/decoding.c#L19
* `DGifGetLine` is taken from GIFLib, code is here: https://github.com/koral--/android-gif-drawable/blob/dev/src/main/jni/giflib/dgif_lib.c#L302
* `DGifGetLine` is used to decode raster and its size must be passed, extraneous pixels have to be skipped. `DGifGetCode` and `DGifGetCodeNext` are intended to read GIF data blocks without decoding but I'm not sure if such kind skipping which you want can be achieved out of the box. As a last resort you can read bytes from source manually till the block terminator.

**Comment by huyduongtu** [comment]
You mean that with my solution (change each frame's size if its size exceeds canvas size), `DGifGetLine` will fail when a frame's size is modified. From that, that frame can not be displayed. Right? Does it cause any crashes?

**Comment by koral--** [comment]
I just diged into `DGifGetLine` source (that part of code comes from GIFLib, I haven't written it myself) and I see that extra bytes are flushed automatically (using `DGifGetCodeNext`), see here: https://github.com/koral--/android-gif-drawable/blob/dev/src/main/jni/giflib/dgif_lib.c#L322
So it looks like, that you can pass raster smaller that image size to `DGifGetLine` and everything should just work.
There is one more important thing. `GifFile->Image.Width` inside `DDGifSlurp` is used only in local scope, so affected saved image in `gifFilePtr->SavedImages` should be also modified (such code for left and top offset is included in my last commit).
