### ISSUE TITLE
Multi-thread conflict in mBuffer when decoding and drawing

### ISSUE THREAD

**Issue by ttonway** [koral--/android-gif-drawable#257]

**Comment by koral--** [comment]
Could you elaborate?

**Comment by ttonway** [comment]
I'm making an app that control gif playing by drag on the screen. I called seekToFrame() in ImageView->onTouchEvent(). Maybe seekToFrame is called too much, sometimes the mBuffer is a black bitmap.
I guess this is a multithread issue.

**Comment by koral--** [comment]
OK, I'll check that.

**Comment by koral--** [comment]
`seekToFrame()` is asynchronous and runs by default in background thread, while `draw()` runs in UI thread. `seekToFrameAndGet()` is synchronous on the other hand.
Drawing is not synchronized to avoid glitches but there is a side effect that frame may be partially rendered when it is drawn in cases like yours.
I would say that it is by design, however if you have better idea feel free to comment or make a PR.

There are several ways to fix your issue, eg.:

1. use `seekToFrameAndGet()` instead of `seekToFrame()`
2. make a custom `ScheduledThreadPool` which executes runnables in UI thread and specify it in `GifDrawableBuilder`
3. make a custom `ScheduledThreadPool`, subclass `GifDrawable` and synchronize drawing with seeking
