### ISSUE TITLE
Why set rwxr-xr-x on outputFile?

### ISSUE THREAD

**Issue by georgiev-martin** [koral--/android-gif-drawable#264]
The [outputFile](https://github.com/koral--/android-gif-drawable/blob/master/src/main/java/pl/droidsonroids/gif/ReLinker.java#L73) in the ReLinker is opened in MODE_PRIVATE. Why set the permissions on it to [world readable/executable](https://github.com/koral--/android-gif-drawable/blob/master/src/main/java/pl/droidsonroids/gif/ReLinker.java#L120)? The parent app will have access to the file anyway.

**Comment by koral--** [comment]
Direct reason is that ReLinker is based on this [patch to chromium](https://codereview.chromium.org/200753002/patch/280001/260004). [Android package installer](http://androidxref.com/6.0.1_r10/xref/frameworks/base/core/jni/com_android_internal_content_NativeLibraryHelper.cpp#284) is also setting those permissions by default. Why they do that? I guess due to historical reasons. As the name suggest shared library is meant to be used by multiple users and most of `.so` files has that permissions by default.
