### ISSUE TITLE
Is there any way to decode one frame only?

### ISSUE THREAD

**Issue by kyze8439690** [koral--/android-gif-drawable#308]
I need to do some animation when initial view, but gifDrawable initial decode seems to be a time-consuming operation, cause my animation being lag. Is there any way to decode only one frame when initial drawable? When animation is finished I can manually continue decoding and auto play the gif. Thank you very much.

**Comment by koral--** [comment]
Actually during `GifDrawable` creation no frames are decoded. GIF header and metadata about each frame is read, but pixel data is skipped. First frame pixels are read when needed.
On the other hand creation involves frame buffer allocation which is the most time consuming operation in most cases.
Direct option to speed up `GifDrawable` creation is to pass some old instance of `GifDrawable` to `GifDrawableBuilder`, in such case Bitmap from it is reused (if it is large enough) instead of allocating new one.
Another way is to use faster input source, `InputStream` is the slowest one and `ByteBuffer` the fastest.
