### ISSUE TITLE
how to set maxheight minheight? it did`t work at xml

### ISSUE THREAD

**Issue by flyou** [koral--/android-gif-drawable#351]
Like  this

                <pl.droidsonroids.gif.GifImageView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center"
                    android:adjustViewBounds="true"
                    android:maxWidth="180dp"
                    android:minHeight="100dp"
                    android:minWidth="100dp"
                    android:maxHeight="180dp"
                    android:scaleType="fitCenter"
                 />
so how to set it in aright way

**Comment by koral--** [comment]
`GifImageView` should work exactly in the same way as `ImageView` in that matter. I'll check it.
What are dimensions of a GIF?

**Comment by koral--** [comment]
I've just checked and it works for me, example in commit linked above.
Note that min widht/height is not guaranteed because parent view may restrict them. See https://developer.android.com/reference/android/view/View.html#attr_android:minWidth

I'll close this issue as unrelated to the library, however feel free to post additional info.
