### ISSUE TITLE
why Different phones have different play speed for the same gifs

### ISSUE THREAD

**Issue by bravekingzhang** [koral--/android-gif-drawable#357]
my code is:
```
GifImageView imageView = (GifImageView) view.findViewById(R.id.iv_plain);
imageView.setImageResource(R.drawable.post_plain);
```
could you help me ?

**Comment by koral--** [comment]
Are those GIF large? Namely have frames containing large number of pixels especially with low durations? If so then there may be a case when rendering a frame takes more time than duration of previous one.
Eg. frame is large and requires 0.02 s to render on weak devices but 0.005 s on faster ones. Previous frame have 0.01 s duration. In such case on weaker phone GIF will be played slower.

**Comment by bravekingzhang** [comment]
Thanks a lot ,but ,could you speed up the frame duration,or provide us API to change it.

**Comment by bravekingzhang** [comment]
Hi @koral-- 

I want ask you another question,could you offer us an api to limit gif play time.
such as limit the time to 2 second to finish play the gif.

or 

offer us api to skip frames,such as only play 1,3,5,7....

**Comment by koral--** [comment]
`setSpeed()` will shorten frame durations but not beyond device performance limit. If rendering takes more time than duration then increasing speed won't have any visible effect.
Frame skipping is not possible in general, because GIFs are incremental, eg. frame 3. may actually contain only differences between 2. and 3. so 2. must still be rendered and cannot be simply skipped. See [here](http://www.imagemagick.org/Usage/anim_basics/#none) for more info.

Frame can be skipped only if next (not skipped) one covers entire canvas and doesn't have transparent pixels. Probably most GIFs in the wild doesn't have such frames, that's why there is no skipping feature in library.

If you want to display large frames on weak devices there 2 options:

1. enable [subsampling](http://static.javadoc.io/pl.droidsonroids.gif/android-gif-drawable/1.2.2/pl/droidsonroids/gif/GifOptions.html#setInSampleSize-int-) 
2. use `GifTextureView` or `GifTexImage2D` instead of other `View`s using `Drawable`s (like `GifImageView`), there are samples in [sample project](https://github.com/koral--/android-gif-drawable/tree/dev/sample)

**Comment by bravekingzhang** [comment]
Thank you very much @koral--
