### ISSUE TITLE
How to resize GifDrawable

### ISSUE THREAD

**Issue by LuffyVim** [koral--/android-gif-drawable#361]
In my own TextView, I try to load a Gif image, but I find that I can not modify the size of the GifDrawable.Can I change the size of GifDrawable?

**Comment by koral--** [comment]
You can use `Drawable#setBounds()`. See sample project: https://github.com/koral--/android-gif-drawable/blob/master/sample/src/main/java/pl/droidsonroids/gif/sample/ImageSpanFragment.java#L30

**Comment by LuffyVim** [comment]
Hi, I follow the sample code, using the `Drawable # setBounds ()` method, but it does not seem to work, This is my code,
```java
final GifDrawable gifDrawable = GifDrawable.createFromResource(getResources(), R.drawable.testgif);
gifDrawable.setBounds(0, 0,  60, 60);
gifDrawable.setCallback(this);
setCompoundDrawablesWithIntrinsicBounds(null, gifDrawable, null, null);
setText(info.title);
setTag(info);
```

**Comment by koral--** [comment]
You haven't said you want compound drawable, so I assumed span.

As the name suggests _setCompoundDrawablesWith**Intrinsic**Bounds_ uses intrinsic bounds, not ones set by `setBounds()`
So there are 2 solutions:

1. Use `setCompoundDrawables()` instead of `setCompoundDrawablesWithIntrinsicBounds()`
2. Subclass `GifDrawable` and override `getIntrinsicHeight()` and `getIntrinsicWidth()`

In case of compound drawables, custom callback is not needed, `TextView` take care of that.

**Comment by LuffyVim** [comment]
Thank you very much for your suggestion, I have not figured out the use of `setCompoundDrawablesWithIntrinsicBounds,` it works very well.
