### ISSUE TITLE
GifImageButton not animate src as "selector"

### ISSUE THREAD

**Issue by UserSty** [koral--/android-gif-drawable#364]
I'm using `pl.droidsonroids.gif.GifImageButton`

but when I set selector to src it doesn't work
 
this src example line:` android:src="@drawable/selector_button_gif"`

this selector example line:
```
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@drawable/icon_gif_1" android:state_selected="true" />
    <item android:drawable="@drawable/icon_gif_2" />
</selector>
```

Can I use a selector, thanks?

**Comment by koral--** [comment]
`android:src` in `GifImageButton` supports only GIF files.

I've just added few solutions for selectors containing GIFs to sample project (commit linked above):

1. Create `StateListDrawable` and add `GifDrawables` as appropriate states:
[sample code in AnimatedSelectorFragment](https://github.com/koral--/android-gif-drawable/blob/dev/sample/src/main/java/pl/droidsonroids/gif/sample/AnimatedSelectorFragment.java#L45-L50)

2. Open selector resource file as XML and parse it:
[sample parser](https://github.com/koral--/android-gif-drawable/blob/dev/sample/src/main/java/pl/droidsonroids/gif/sample/AnimatedSelectorDrawableGenerator.java)
and its [usage](https://github.com/koral--/android-gif-drawable/blob/dev/sample/src/main/java/pl/droidsonroids/gif/sample/AnimatedSelectorFragment.java#L41)

3. Create `StateListDrawable` subclass and override `inflate` method. Parsing code is almost the same as in previous solution but everything is encapsulated in drawable, no code outside needed.
[GifSelectorDrawable](https://github.com/koral--/android-gif-drawable/blob/dev/sample/src/main/java/pl/droidsonroids/gif/sample/GifSelectorDrawable.java)
and use it instead of `selector`: [in xml](https://github.com/koral--/android-gif-drawable/blob/dev/sample/src/main/res/drawable-v24/selector.xml#L2)
That works in API 24+, see [Drawable javadoc](https://developer.android.com/reference/android/graphics/drawable/Drawable.html#Custom) for more info.

**Comment by UserSty** [comment]
Thanks, I will try

**Comment by UserSty** [comment]
How use tis samples for android:src / setImageResource , please?

**Comment by UserSty** [comment]
It's working!
