### ISSUE TITLE
libpl_droidsonroids_gif.so file size of the explosion

### ISSUE THREAD

**Issue by xiaopansky** [koral--/android-gif-drawable#383]
I noticed a single libpl_droidsonroids_gif.so file size from the 1.1.7 version of the 30KB soaring to the current 300KB, I would like to know what happened? Now the size of some difficult to accept!

**Comment by koral--** [comment]
It doesn't seem to be intended. I'll investigate this.

**Comment by koral--** [comment]
There 2 reasons:

1. in version 1.1.7 there was 2 separate `.so` files (additionally `libpl_droidsonroids_gif_surface.so`) now, everything is located in `libpl_droidsonroids_gif.so`
2. version 1.2.3 started using `externalNativeBuild` from Android Gradle plugin instead of custom gradle scripts for NDK to compile native sources

Current sources compiled using old script gives `libpl_droidsonroids_gif.so` having 42KB.
I'll fix it ASAP.

**Comment by koral--** [comment]
It turns out that `-g` option is added implicitly when using `externalNativeBuild` which causes adding debuging symbols and library size growth.

Fixed in 1.2.5-SNAPSHOT. Size of whole AAR reduced from 881505 to 264435 bytes.
Thanks for the report.
