### ISSUE TITLE
 How to get.Gif first frame

### ISSUE THREAD

**Issue by 15189611** [koral--/android-gif-drawable#384]
How to get.Gif first frame?
thanks

**Comment by koral--** [comment]
If you already have `GifDrawable` instance you can use [seekToFrameAndGet](https://static.javadoc.io/pl.droidsonroids.gif/android-gif-drawable/1.2.5/pl/droidsonroids/gif/GifDrawable.html#seekToFrameAndGet-int-)
Otherwise you can use [GifDecoder](https://static.javadoc.io/pl.droidsonroids.gif/android-gif-drawable/1.2.5/pl/droidsonroids/gif/GifDecoder.html#seekToFrame-int-android.graphics.Bitmap-)
