### ISSUE TITLE
How to load a large gif in listview

### ISSUE THREAD

**Issue by JNYoung** [koral--/android-gif-drawable#388]
I have to load a large gif(larger than 2.3M) in listview(recyclerview) due to the product need, but I found the gifImageView has a bad performance due to the gc, and the giftexureview has some problems as issue #356 has said.
Is there some good solutions when I need to load a large gif in listview?

--a developer from China(so forgive my bad expression:)

**Comment by koral--** [comment]
If GIF is large due to its frames sizes (number of pixels) and in `ListView` it is displayed smaller than original you may use `GifImageView` with subsampling enabled (see [javadoc](http://static.javadoc.io/pl.droidsonroids.gif/android-gif-drawable/1.2.5/pl/droidsonroids/gif/GifOptions.html#setInSampleSize-int-) for more info). This will lower number of processed pixels thus improve performance.

**Comment by JNYoung** [comment]
tried，but not word
the first frame is also to large for the listview rendering when fling
