### ISSUE TITLE
How to cancel Gif loading (alternative to Glide.clear())

### ISSUE THREAD

**Issue by storix** [koral--/android-gif-drawable#390]
When using `RecyclerView` with [Glide](https://github.com/bumptech/glide) they recommend to call Glide.clear()  in `onViewRecycled`  to cancel the previous request like this:

```
    override fun onViewRecycled(holder: RecyclerView.ViewHolder) {
        super.onViewRecycled(holder)
        Glide.clear(holder.gifImageView)
    }
```
Is there an analogous method in this library?  

Basically, what I need is to be able to cancel the previous Gif loading operations when the user scrolls down the `RecyclerView`.

I saw in the [sample](https://github.com/koral--/android-gif-drawable/blob/master/sample/src/main/java/pl/droidsonroids/gif/sample/sources/GifSourcesAdapter.java#L38) app that you are using `GifDrawableBuilder` to reuse `GifDrawable`. However, it is a bit unclear whether those drawables will be automatically released from memory in case of configuration change. And what about fast scrolling? Are there any way to quickly release the off-screen `GifDrawable`s? Thanks.

**Comment by koral--** [comment]
To immediately release resources allocated by `GifDrawable` you can use [GifDrawable#recycle()](http://static.javadoc.io/pl.droidsonroids.gif/android-gif-drawable/1.2.5/pl/droidsonroids/gif/GifDrawable.html#recycle--). This is the only method which do that, no matter where Drawable is used.

With `GifDrawableBuilder` you can reuse frame buffer of no longer used `GifDrawable` instead of allocating new one. If old drawable has enough dimensions it will be reused, if not it won't be touched, you may recycle it yourself if you want.

In sample app it used to deal with fast scrolling.
