### ISSUE TITLE
Problems that can't play when using selectors?

### ISSUE THREAD

**Issue by 303635955** [koral--/android-gif-drawable#432]

**Comment by 303635955** [comment]
Problems that can't play when using selectors?

**Comment by koral--** [comment]
I guess you are trying to use GIFs directly in selector XML.
That won't work because they will be interpreted as plain bitmaps. It's not a bug but default Android framework behavior.
You need to create custom selector.
Solutions are listed here: https://github.com/koral--/android-gif-drawable/issues/364#issuecomment-263093860
2 of them are also included in sample project: https://github.com/koral--/android-gif-drawable/blob/dev/sample/src/main/java/pl/droidsonroids/gif/sample/AnimatedSelectorFragment.kt
