### ISSUE TITLE
Crash caused by finalize()

### ISSUE THREAD

**Issue by areful** [koral--/android-gif-drawable#445]
Can you remove method finalize() from GifInfoHandle.java? This method is not recommended for programming.

In some case and some special phones, this may cause an TimeoutException. And this problem trouble us for a long time.

Here a sample  which cause this exception. Run app and press HOME key, and waiting for about 10s after gc() called, then the crash will occurred.

public class MainActivity extends AppCompatActivity {
    private BugReceiver mReceiver;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }

    @Override
    protected void onStart() {
        Log.d("gj--", "onStart()");
        super.onStart();
        mReceiver = new BugReceiver();
        registerReceiver(mReceiver, new IntentFilter(Intent.ACTION_CALL));
    }

    @Override
    protected void onStop() {
        Log.d("gj--", "onStop()");
        super.onStop();
        if (mReceiver != null) {
            unregisterReceiver(mReceiver);
            mReceiver = null;

            System.gc();
        }
    }

    /**
     * BugReceiver
     */
    private class BugReceiver extends BroadcastReceiver {
        @Override
        public void onReceive(Context context, Intent intent) {
        }

        @Override
        protected void finalize() throws Throwable {
            Log.d("gj--", "finalize()");

            try {
                for (int i = 1; i <= 13; i++) {
                    Thread.sleep(10 * 1000);
                    Log.d("gj--", String.format("sleep %ds", i * 10));
                }
            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                Log.d("gj--", "super.finalize()");
                super.finalize();
            }
        }
    }
}

**Comment by areful** [comment]
We can write a method to replace finalize(): 
when objects are no longer used, invoke this method in our app first. This may not cause exceptions.
I wish I could describe it more clearly.

**Comment by koral--** [comment]
There is a such method. It is called [recycle()](https://static.javadoc.io/pl.droidsonroids.gif/android-gif-drawable/1.2.7/pl/droidsonroids/gif/GifDrawable.html#recycle--). If you call it, finalizer won't do anything.
I know that finalizer is not recommended, but there is no other way to automatically release resources allocated native way. Garbage collector won't touch them. 
That's why classes like [MotionEvent](https://developer.android.com/reference/android/view/MotionEvent.html) or [Bitmap](https://developer.android.com/reference/android/graphics/Bitmap.html) have finalizers.

Snippet you posted do not include any code from this library. Do you have any example when exception is thrown from `GifInfoHandle` finalizer.

**Comment by areful** [comment]
Thanks very much *^-^*
