### ISSUE TITLE
conflict with unity applcation

### ISSUE THREAD

**Issue by humayuntanwar** [koral--/android-gif-drawable#512]
every time i m trying to compile the library with my android application, the unity app inside the application stops working, resulting in failure to initialize unity application.
the reason maybe is because i m using maven 🔢 
 maven {
            url "https://maven.google.com"
        }
. you can guys help.

**Comment by koral--** [comment]
Could you post the error you are getting?

**Comment by humayuntanwar** [comment]
every time i launch the unity activity while which library is complied i get the error:
"failed to initialize application , your hardware does not support it"
if i remove this library the unity activity is working fine

**Comment by koral--** [comment]
OK, I'll check that.

**Comment by EdotShreya** [comment]
Even I am getting the same error.

**Comment by koral--** [comment]
Sorry for the delay. I'm not familiar with Unity, additionally it requires Windows or macOS but I usually use Linux so my work on this task is very slow.
Could you share a minimal sample project which reproduce this issue? @EdotShreya @humayuntanwar  
It should speed up my investigation.

**Comment by Cy-Appxplore** [comment]
The problem is due to the abi, i'm not so sure myself but originally the problem is with gif-drawable still using mips. I thought changing the version to 1.2.13 and above fixed it, however it can only be built but not runnable (hence the "failed to initialize application" problem).

My workaround is just adding ndk {abiFilters 'armeabi-v7a' 'x86'} to build.gradle. For unity, you might need to build with gradle and generate the custom gradle template by unity and edit inside it. Problem solved.

**Comment by koral--** [comment]
Thanks, it seems that unity has its own 32-bit native libs without corresponding 64-bit versions.
App must contain either all or none 64-bit libraries. If there only some of them provided then trying to load missing one will fail.

A short term workaround is indeed adding a filter:
https://corbt.com/posts/2015/09/18/mixing-32-and-64bit-dependencies-in-android.html

But such apps won't be accepted by Google Play store soon: 
https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html

Unity needs to updated before that time.
