### ISSUE TITLE
FloatingActionButton src in Gif

### ISSUE THREAD

**Issue by AlexLutinNoir** [koral--/android-gif-drawable#552]
Hello there,
I was trying to implement a floating action button with a gif as its icon inside, would it be possible with android-gif-drawable?
I tried to add the bare src in gif, and it didn't animate, I also tried to enter pl.droidsonroids.gif.GifImageView inside the floating button and it didn't show at all, any suggestion if someone hasever tried it ?
Thanks in advance.

**Comment by koral--** [comment]
Sorry for the delay. The simplest solution is to create `GifDrawable` instance and then call `floatingActionButton.setImageDrawable(gifDrawable)`.

Specifying `src` attribute inside FAB tag won't work unless you create a subclass of FAB and add custom attribute parsing. Just like `GifImageButton` is a subclass of `ImageButton` (you can look at the source code).

Putting any tag inside FAB tag won't work because FAB is not a ViewGroup, it cannot contain child Views.
