### ISSUE TITLE
What will happen if I never call recycle() ？memory leak？

### ISSUE THREAD

**Issue by 1727** [koral--/android-gif-drawable#624]

**Comment by koral--** [comment]
It will be called by finalizer just before garbage collection. However, it is undefined when exactly garbage collection will be triggered. It won't be triggered as long as there is enough free java heap space.

There won't be a leak because everything is still reachable and can be released.
Depending on what else is happening in your process and what is the source of GIF, how many not recycled objects you have, what is their source etc. you may encounter various errors. E.g. you may run out of available file descriptors and won't be able to open new file.

**Comment by 1727** [comment]
Thanks
