### ISSUE TITLE
ERROR: Manifest merger failed

### ISSUE THREAD

**Issue by Bhattanitesh** [koral--/android-gif-drawable#676]
uses-sdk:minSdkVersion 15 cannot be smaller than version 17 declared in library [pl.droidsonroids.gif:android-gif-drawable:1.2.17] C:\Users\Acer\.gradle\caches\transforms-2\files-2.1\26d321933e2551a0ef10a2849445588d\AndroidManifest.xml as the library might be using APIs not available in 15
	Suggestion: use a compatible library with a minSdk of at most 15,
		or increase this project's minSdk version to at least 17,
		or use tools:overrideLibrary="pl.droidsonroids.gif" to force usage (may lead to runtime failures)

Any Solution for this?

**Comment by Bhattanitesh** [comment]
> uses-sdk:minSdkVersion 15 cannot be smaller than version 17 declared in library [pl.droidsonroids.gif:android-gif-drawable:1.2.17] C:\Users\Acer.gradle\caches\transforms-2\files-2.1\26d321933e2551a0ef10a2849445588d\AndroidManifest.xml as the library might be using APIs not available in 15
> Suggestion: use a compatible library with a minSdk of at most 15,
> or increase this project's minSdk version to at least 17,
> or use tools:overrideLibrary="pl.droidsonroids.gif" to force usage (may lead to runtime failures)
> 
> Any Solution for this?

I think I got the solution.
After changing pl.droidsonroids.gif:android-gif-drawable:1.2.17 to pl.droidsonroids.gif:android-gif-drawable:1.2.15, The gradle synced

**Comment by koral--** [comment]
Minimum SDK version for this library since v1.2.16 is 17.

Suggested fixes are listed in the message:
1. use a compatible library with a minSdk of at most 15, (that's what you suggested in your 2nd post)
2. or increase this project's minSdk version to at least 17,
3. or use tools:overrideLibrary="pl.droidsonroids.gif" to force usage (may lead to runtime failures)

If you really need to support users with APIs 15 and 16 (officially 1.5% of the market at the time of writing) choose option 1.
If you can increase min sdk in your app choose option 2.
Option 3. is not recommended, however there is a chance that it will work in your use case.
