### ISSUE TITLE
Version 1.2.19 causing compile time errors.

### ISSUE THREAD

**Issue by nachikamod** [koral--/android-gif-drawable#740]
Version 1.2.19 causing unresolved class in layout files causing compile time errors.

**Comment by koral--** [comment]
Could you attach a sample code which reproduces this issue?
With amount of info you provided nothing can be done.

**Comment by nachikamod** [comment]
Sorry I believe this is my config issue

Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 17 declared in library [pl.droidsonroids.gif:android-gif-drawable:1.2.19] C:\Users\nachi\.gradle\caches\transforms-2\files-2.1\5182bd6ddba5314fe20351ac47f342d4\jetified-android-gif-drawable-1.2.19\AndroidManifest.xml as the library might be using APIs not available in 16
	Suggestion: use a compatible library with a minSdk of at most 16,
		or increase this project's minSdk version to at least 17,
		or use tools:overrideLibrary="pl.droidsonroids.gif" to force usage (may lead to runtime failures)

![Screenshot (13)](https://user-images.githubusercontent.com/47713768/85503900-69d85400-b608-11ea-9188-c1ebf24c1c3e.png)
![Screenshot (14)](https://user-images.githubusercontent.com/47713768/85503903-6d6bdb00-b608-11ea-8c87-ef6890ab1353.png)

**Comment by koral--** [comment]
Sorry for the delay.
Indeed the min sdk version required by this library is currently 17.
You need to follow instructions you've pasted. You have 2 options:
* increase min sdk of your app to 17
* use `tools:overrideLibrary`. However, this is unsupported and you need to ensure that no API available since  level 17 is used in your particular case.
