### ISSUE TITLE
Gif is decoded as 1 frame animation

### ISSUE THREAD

**Issue by 5ALEKSEY** [koral--/android-gif-drawable#801]
Hello 😇

I've found an issue on my working project. I have faced with a problem when some of our GIF display incorrectly.

I've investigated and found out that:
1) **SampleSize** doesn't work if the value grater then 1 was passed 
(But as I see, you are already know it and even managed to fix 👍 Waiting for the release)
2) GIF is decoded as 1 frame animation. 

Let's talk about second one.

Our `GifDrawable` creating has next steps:
```java
GifOptions gifOptions = new GifOptions();
gifOptions.setInSampleSize(gifInSampleSize); // 'gifInSampleSize' was calculated before
drawable = new GifDrawableBuilder()
            .from(mContext.getContentResolver(), gifUri)
            .options(gifOptions)
            .build();
drawable.setLoopCount(0);
```
As the result `GifDrawable` is: `GIF: size: 1999x1999, frames: 1, error: 107`

Here we can see 107 error and only 1 fetched frame (but actually it has more frames 😞)

About GIF. Nothing special here except of "why is it so big??? 🙃".
Yes, it is really big. And, btw, `gifInSampleSize = 4` here 🤫 
It was found during the testing of different sizes.

How was this GIF born:
- usual GIF was downloaded from [site](https://giphy.com/gifs/KYN8l3oTD8vY5rHh0s)
- gif size was changed via [online converter](https://www.iloveimg.com/ru/resize-image/resize-gif#resize-options,pixels).

I request you help in case of at least explanation "why it was decoded as 1 frame". I don't know, probably, online converter made it's own dirty monkey tricks and GIF file become broken. So, I would appreciate any of your help and explanation here.

P.S. I have tested this gif with your sample project and added this 'broken' GIF to `drawable` resources. Result is the same. You can reproduce it by yourself, I'll attach it.
P.P.S. GIF playing is okey for my PC (more than 1 frame animation)

[broken_cat.zip](https://github.com/koral--/android-gif-drawable/files/9072638/broken_cat.zip)

**Comment by koral--** [comment]
Frames of that GIF are located outside the canvas.
```
% gifsicle -I broken_cat.gif
* broken_cat.gif 19 images
  logical screen 3999x3999
  global color table [256]
  background 0
  loop forever
  + image #0 3999x3999
    disposal asis delay 2.00s
  + image #1 3393x3999 at 993,2014 transparent 0
...
```
The entire canvas has size 3999x3999 px, but eg. image #1 having size 3393x3999 starts at offset 993,2014 so it requires canvas which has at least 4386x6013 px.

Some GIF viewers try to "fix" such issues either by extending the canvas or cropping parts which exceed the bounds.
In this library, currently such cases are treated as errors. In the past there were workarounds but they turns out to be too complicated to support. This library does not buffer the source but reads frames as needed. Sources may be modified in the meantime.
Viewers like desktop apps can buffer entire decoded GIF in memory and may not need to read it from the source again so applying workarounds is easier.

Regarding decoding as 1 frame. In this library (and probably in most viewers) there is a rule that the content successfully decoded (what exactly can be successful depends among the others on workarounds for broken images) so far is kept and after error is encountered then new frames are not decoded. As you can see on the gifsicle output image #0 is correct and the next one is too large, so there is only 1 valid image.

Regarding error reported. In this case it should be `1000 Image not confined`. I'll fix that.

**Comment by 5ALEKSEY** [comment]
Oh, I see 🤔

So, I believe in a future you will manage to find a great and easy approach/way to "support" such frameSize-broken GIFs.

Anyway, thanks a lot for your help, explanation and really quick answer 👍👍👍
